# evoclim::homogval.evol(homog.param ="ths200m0",
#               stations="swissmean.north.high",
#               begin.date = "186401",
#               end.date = "202408",
#               ##add.current.mo = TRUE,
#               add.current.mo = FALSE,
#               write.txt = TRUE,
#               val.resolution = "m",
#               anomalies = TRUE,
#               begin.refperiod = 1991,
#               end.refperiod = 2020,
#               data.line = "loess",
#               loess.param = list (window=30,conf.int=TRUE,do.diff=TRUE,y1=1885,y2=NULL,y1.as.mean=TRUE,add.exp.val=TRUE),
#               add.ranking.high = TRUE,
#               add.ranking.low = FALSE,
#               add.legend = TRUE,
#               add.source = TRUE,
#               out.path = "current",
#               language = "d",
#               sig.tool.time = TRUE,
#               axis.cex = 1.2)
# 
# evoclim::homogval.evol(homog.param ="ths200m0",
#                        stations="swissmean.north.low",
#                        begin.date = "186401",
#                        end.date = "202408",
#                        ##add.current.mo = TRUE,
#                        add.current.mo = FALSE,
#                        write.txt = TRUE,
#                        val.resolution = "m",
#                        anomalies = TRUE,
#                        begin.refperiod = 1991,
#                        end.refperiod = 2020,
#                        data.line = "loess",
#                        loess.param = list (window=30,conf.int=TRUE,do.diff=TRUE,y1=1885,y2=NULL,y1.as.mean=TRUE,add.exp.val=TRUE),
#                        add.ranking.high = TRUE,
#                        add.ranking.low = FALSE,
#                        add.legend = TRUE,
#                        add.source = TRUE,
#                        out.path = "current",
#                        language = "d",
#                        sig.tool.time = TRUE,
#                        axis.cex = 1.2)
# 
# evoclim::homogval.evol(homog.param ="ths200m0",
#                        stations="swissmean.south",
#                        begin.date = "186401",
#                        end.date = "202408",
#                        ##add.current.mo = TRUE,
#                        add.current.mo = FALSE,
#                        write.txt = TRUE,
#                        val.resolution = "m",
#                        anomalies = TRUE,
#                        begin.refperiod = 1991,
#                        end.refperiod = 2020,
#                        data.line = "loess",
#                        loess.param = list (window=30,conf.int=TRUE,do.diff=TRUE,y1=1885,y2=NULL,y1.as.mean=TRUE,add.exp.val=TRUE),
#                        add.ranking.high = TRUE,
#                        add.ranking.low = FALSE,
#                        add.legend = TRUE,
#                        add.source = TRUE,
#                        out.path = "current",
#                        language = "d",
#                        sig.tool.time = TRUE,
#                        axis.cex = 1.2)
# 
# evoclim::homogval.evol(homog.param ="ths200m0",
#                        stations="swissmean",
#                        begin.date = "186401",
#                        end.date = "202408",
#                        ##add.current.mo = TRUE,
#                        add.current.mo = FALSE,
#                        write.txt = TRUE,
#                        val.resolution = "m",
#                        anomalies = TRUE,
#                        begin.refperiod = 1991,
#                        end.refperiod = 2020,
#                        data.line = "loess",
#                        loess.param = list (window=30,conf.int=TRUE,do.diff=TRUE,y1=1885,y2=NULL,y1.as.mean=TRUE,add.exp.val=TRUE),
#                        add.ranking.high = TRUE,
#                        add.ranking.low = FALSE,
#                        add.legend = TRUE,
#                        add.source = TRUE,
#                        out.path = "current",
#                        language = "d",
#                        sig.tool.time = TRUE,
#                        axis.cex = 1.2)
# 
# evoclim::homogval.evol(homog.param ="ths200m0",
#                        stations="swissmean",
#                        begin.date = "186401",
#                        end.date = "202408",
#                        ##add.current.mo = TRUE,
#                        add.current.mo = FALSE,
#                        write.txt = TRUE,
#                        val.resolution = "m",
#                        anomalies = FALSE,
#                        begin.refperiod = 1991,
#                        end.refperiod = 2020,
#                        data.line = "loess",
#                        loess.param = list (window=30,conf.int=TRUE,do.diff=TRUE,y1=1885,y2=NULL,y1.as.mean=TRUE,add.exp.val=TRUE),
#                        add.ranking.high = TRUE,
#                        add.ranking.low = FALSE,
#                        add.legend = TRUE,
#                        add.source = TRUE,
#                        out.path = "current",
#                        language = "d",
#                        sig.tool.time = TRUE,
#                        axis.cex = 1.2)
# 
#Filenames testdate incl regional info
#ths200m0.swissmean.m.aug.1864.2024.abs.txt
#ths200m0.swissmean.m.aug.1864.2024.anom.txt
#ths200m0.swissmean_north_low.m.aug.1864.2024.anom.txt
#ths200m0.swissmean_south.m.aug.1864.2024.anom.txt
