``` {r echo=FALSE, results = "hide"}
all_prec_devs_above_norm <- all(regdiff$allvalues_P > 105)
all_prec_devs_below_norm <- all(regdiff$allvalues_P < 95)
all_prec_devs_normal <- all(regdiff$allvalues_P <= 105) & all(regdiff$allvalues_P >= 95)
most_prec_devs_above_norm <- regdiff$anteil_ueber_P > 0.7 & regdiff$anteil_ueber_P < 1
most_prec_devs_below_norm <- regdiff$anteil_unter_P > 0.7 & regdiff$anteil_unter_P < 1
most_prec_devs_normal <- regdiff$anteil_bereich_P > 0.7 & regdiff$anteil_bereich_P < 1

qr_low <- round(quantile(regdiff$allvalues_P,probs=0.2)/10, digits=0)*10
qr_high <- round(quantile(regdiff$allvalues_P,probs=0.8)/10, digits=0)*10

moment01 <- ifelse(bulletin$provisional, "bis zum gestrigen Tag ", "") 
moment02 <- ifelse(bulletin$provisional, "bis kurz vor Schluss ", "")
```

`r ifelse(all_prec_devs_above_norm, glue::glue("Die monatlichen Niederschlagsmengen im {month_str(bulletin$month)} {bulletin$year} waren {moment01}schweizweit überdurchschnittlich."), "")``r ifelse(all_prec_devs_below_norm, glue::glue("Der {month_str(bulletin$month)} {bulletin$year} brachte {moment01}schweizweit unterdurchschnittliche Niederschlagsmengen."), "")``r ifelse(all_prec_devs_normal, glue::glue("Die monatliche Niederschlagssumme im {month_str(bulletin$month)} {bulletin$year} lag {moment01}schweizweit im Bereich des Mittels über Referenzperiode 1991-2020."), "")``r ifelse(most_prec_devs_above_norm, glue::glue("Die monatlichen Niederschlagsmengen im {month_str(bulletin$month)} {bulletin$year} waren {moment01}verbreitet überdurchschnittlich."), "")``r ifelse(most_prec_devs_below_norm, glue::glue("Der {month_str(bulletin$month)} {bulletin$year} brachte {moment01}verbreitet unterdurchschnittliche Niederschlagsmengen."), "")``r ifelse(most_prec_devs_normal, glue::glue("Die monatliche Niederschlagssumme im {month_str(bulletin$month)} {bulletin$year} lag {moment01}verbreitet im Bereich des Mittels über Referenzperiode 1991-2020."), "")` `r ifelse(qr_low <= 50, glue::glue("Regional wurden {moment02}weniger als {qr_low}&nbsp;% eines durchschnittlichen {month_str(bulletin$month)}niederschlags verzeichnet."), "")``r ifelse(qr_high >= 150, glue::glue("Gebietsweise betrug die gefallene Niederschlagssumme {moment02}mehr als {qr_high}&nbsp;% der Referenzperiode."), "")`
