

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Klimawandel im Monat

Der globale Klimawandel betrifft auch die Schweiz. Die Temperatur steigt seit der vorindustriellen Zeit in allen Jahreszeiten an. `r if (swissmean$signif<=(1-swissmean$loess$p.val)) {paste0("Auch im ",bulletin$month_str," ist der Temperaturanstieg seit der vorindustriellen Referenzperiode 1871-1900 signifikant. Die Monatsmitteltemperatur im ",bulletin$month_str," ist in den letzten gut ",swissmean$y_since_preind," Jahren um ",swissmean$climate_change_signal[2],"&nbsp;°C gestiegen, von ",round(swissmean$loess$val1,1),"&nbsp;°C auf ",round(swissmean$loess$val2,1),"&nbsp;°C im aktuellen Klimamittel (Endpunkt der schwarzen Klima-Trendlinie). Berücksichtigt man die Unsicherheiten der Trendschätzung, ergibt dies für den ",bulletin$month_str," im landesweiten Mittel eine Temperaturzunahme von ",swissmean$climate_change_signal[1]," bis ",swissmean$climate_change_signal[3],"&nbsp;°C von der vorindustriellen Referenzperiode 1871-1900 bis heute.")} else {paste0("Auf monatlichen Zeitskalen ist die Variabilität so stark, dass es trotz des klaren Klimaänderungssignals in den Jahreszeiten sein kann, dass einzelne Monate vorübergehend keinen signifikanten Temperaturunterschied zwischen der heutigen Zeit und der vorindustriellen Referenzperiode aufweisen. So ist es aktuell im ",bulletin$month_str,". Der Monat weist im Jahr ",bulletin$year," eine Spannweite der Temperaturveränderung gegenüber der vorindustriellen Referenzperiode von ",swissmean$climate_change_signal[1]," bis ",swissmean$climate_change_signal[3],"&nbsp;°C auf.")}`

Der Schwankungsbereich der Monatstemperaturen um die Klima-Trendlinie ist in Abbildung X mit gestrichelten Linien angedeutet. Liegt ein `r bulletin$month_str` ausserhalb dieses Bereichs, gilt er als aussergewöhnlich im Vergleich mit dem aktuellen Klimazustand. Mit der Monatsdurchschnittstemperatur von `r swissmean$curr_temp`&nbsp;°C liegt der `r bulletin$month_str` `r bulletin$year` `r if (swissmean$curr_temp > swissmean$loess_bounds[2]) {"über dem"}``r if (swissmean$curr_temp<swissmean$loess_bounds[1]) {"unter dem"}``r if (swissmean$curr_temp <= swissmean$loess_bounds[2] & swissmean$curr_temp >= swissmean$loess_bounds[1]) {"im"}` Schwankungsbereich. `r if (swissmean$curr_temp>swissmean$loess_bounds[2]) {"Der Monat war damit für das aktuelle Klima zu warm."}``r if (swissmean$curr_temp<swissmean$loess_bounds[1]) {"Der Monat war damit für das aktuelle Klima zu kalt."}``r if (swissmean$curr_temp <= swissmean$loess_bounds[2] & swissmean$curr_temp >= swissmean$loess_bounds[1]) {"Der Monat passt damit zum aktuellen Klimazustand."}``r if (swissmean$curr_temp <= swissmean$loess_bounds[2] & swissmean$curr_temp >= swissmean$loess_bounds[1] & swissmean$curr_rank<10) {paste0(" Dies, obschon der Monat mit Rang ",swissmean$curr_rank," zu den wärmsten seit Messbeginn ",swissmean$meas_start," gehört.")}`
