
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Der globale Klimawandel betrifft auch die Schweiz. Die Temperatur steigt seit der vorindustriellen Zeit in allen Jahreszeiten an. `r if (swissmean$signif<=(1-swissmean$loess$p.val)) {paste0("Auch im ",month_str(bulletin$month)," ist der Temperaturanstieg seit der vorindustriellen Referenzperiode 1871-1900 signifikant. Die Monatsmitteltemperatur im ",month_str(bulletin$month)," ist in den letzten gut ",swissmean$y_since_preind," Jahren um ",swissmean$climate_change_signal[2],"&nbsp;°C gestiegen, von ",round(swissmean$loess$val1,1),"&nbsp;°C auf ",round(swissmean$loess$val2,1),"&nbsp;°C im aktuellen Klimamittel (Endpunkt der schwarzen Klima-Trendlinie). Berücksichtigt man die Unsicherheiten der Trendschätzung, ergibt dies für den ",month_str(bulletin$month)," im landesweiten Mittel eine Temperaturzunahme von ",swissmean$climate_change_signal[1],"&nbsp;°C bis ",swissmean$climate_change_signal[3],"&nbsp;°C von der vorindustriellen Referenzperiode 1871-1900 bis heute.")} else {paste0("Auf monatlichen Zeitskalen ist die Variabilität so stark, dass es trotz des klaren Klimaänderungssignals in den Jahreszeiten sein kann, dass einzelne Monate vorübergehend keinen signifikanten Temperaturunterschied zwischen der heutigen Zeit und der vorindustriellen Referenzperiode aufweisen. So ist es aktuell im ",month_str(bulletin$month),". Der Monat weist im Jahr ",bulletin$year," eine Spannweite der Temperaturveränderung gegenüber der vorindustriellen Referenzperiode von ",swissmean$climate_change_signal[1]," bis ",swissmean$climate_change_signal[3],"&nbsp;°C auf.")}`

<!-- Hier auch bounds2 noch einbeziehen, was darüber oder darunter liegt, gilt als extrem warm oder kalt für das aktuelle Klima; Auch möglich, wenn ein Monat nicht extrem war: Beispiele von extrem warmen und extrem kalten Jahren für das damalige Klima nennen -->

Der Schwankungsbereich der Monatstemperaturen um die Klima-Trendlinie ist in Abbildung X mit gestrichelten Linien angedeutet. Liegt ein `r month_str(bulletin$month)` ausserhalb dieses Bereichs, gilt er als aussergewöhnlich im Vergleich mit dem aktuellen Klimazustand. Dies ist bei `r month_str(bulletin$month)`temperaturen unterhalb von `r swissmean$loess_bounds1[1]`&nbsp;°C bzw. oberhalb von `r swissmean$loess_bounds1[2]`&nbsp;°C der Fall. 

<!-- Liegt die Temperatur ausserhalb des Bereichs zwischen `r swissmean$loess_bounds2[1]`&nbsp;°C und `r swissmean$loess_bounds2[2]`&nbsp;°C, sprechen wir von einer extremen Abweichung vom aktuellen Klimamittel. In diese Kategorie fallen in der Reihe des Schweizer Temperaturmittels seit 1864 nur einzelne Monate.  -->

Mit der Monatsdurchschnittstemperatur von `r swissmean$curr_temp`&nbsp;°C lag der `r month_str(bulletin$month)` `r bulletin$year` `r if (swissmean$curr_temp > swissmean$loess_bounds1[2]) {"über dem"}``r if (swissmean$curr_temp<swissmean$loess_bounds1[1]) {"unter dem"}``r if (swissmean$curr_temp <= swissmean$loess_bounds1[2] & swissmean$curr_temp >= swissmean$loess_bounds1[1]) {"im"}` Schwankungsbereich. `r if (swissmean$curr_temp>swissmean$loess_bounds1[2]) {"Der Monat war damit für das aktuelle Klima aussergewöhnlich warm."}``r if (swissmean$curr_temp<swissmean$loess_bounds1[1]) {"Der Monat war damit für das aktuelle Klima aussergewöhnlich kalt."}``r if (swissmean$curr_temp <= swissmean$loess_bounds1[2] & swissmean$curr_temp >= swissmean$loess_bounds1[1]) {"Die Monatstemperatur passt damit zum aktuellen Klimazustand."}``r if (swissmean$curr_temp <= swissmean$loess_bounds1[2] & swissmean$curr_temp >= swissmean$loess_bounds1[1] & swissmean$curr_rank<10) {paste0(" Dies, obschon der Monat mit Rang ",swissmean$curr_rank," zu den wärmsten seit Messbeginn ",swissmean$meas_start," gehört. Dies zeigt eindrücklich, wie stark sich das Klima im ",month_str(bulletin$month)," verändert hat.")}`
