``` {r echo=FALSE, results = "hide"}
all_prec_devs_above_norm <- all(regdiff$allvalues_P > 105)
all_prec_devs_below_norm <- all(regdiff$allvalues_P < 95)
all_prec_devs_normal <- all(regdiff$allvalues_P <= 105) & all(regdiff$allvalues_P >= 95)
most_prec_devs_above_norm <- regdiff$anteil_ueber_P > 0.7 & regdiff$anteil_ueber_P < 1
most_prec_devs_below_norm <- regdiff$anteil_unter_P > 0.7 & regdiff$anteil_unter_P < 1
most_prec_devs_normal <- regdiff$anteil_bereich_P > 0.7 & regdiff$anteil_bereich_P < 1

qr_low <- round(quantile(regdiff$allvalues_P,probs=0.2)/10, digits=0)*10
qr_high <- round(quantile(regdiff$allvalues_P,probs=0.8)/10, digits=0)*10

moment01 <- ifelse(bulletin$provisional, "Fino a ieri ", "") 
moment02 <- ifelse(bulletin$provisional, "fino alla giornata di ieri ", "")
L <- ifelse(bulletin$provisional, "l", "L")
```

`r ifelse(all_prec_devs_above_norm, glue::glue("La somma delle precipitazioni di {tolower(month_str(bulletin$month))} {bulletin$year} risulta superiore alla media in tutta la Svizzera."), "")``r ifelse(all_prec_devs_below_norm, glue::glue("{moment01}{L}a somma delle precipitazioni di {tolower(month_str(bulletin$month))} {bulletin$year} risultava inferiore alla media in tutta la Svizzera."), "")``r ifelse(all_prec_devs_normal, glue::glue("{moment01}{L}a somma delle precipitazioni di {tolower(month_str(bulletin$month))} {bulletin$year} risultava vicina alla media del periodo di riferimento 1991-2020 in tutta la Svizzera."), "")``r ifelse(most_prec_devs_above_norm, glue::glue("La somma delle precipitazioni di {tolower(month_str(bulletin$month))} {bulletin$year} risulta superiore alla media in molte regioni."), "")``r ifelse(most_prec_devs_below_norm, glue::glue("{moment01}{L}a somma delle precipitazioni di {tolower(month_str(bulletin$month))} {bulletin$year} risultava inferiore alla media in molte regioni."), "")``r ifelse(most_prec_devs_normal, glue::glue("{moment01}{L}a somma delle precipitazioni di {tolower(month_str(bulletin$month))} {bulletin$year} risultava vicina alla media del periodo di riferimento 1991-2020 in molte regioni."), "")` `r ifelse(qr_low <= 50, glue::glue("In alcune regioni {moment02}la somma delle precipitazioni mensili è stata meno del {qr_low} % delle precipitazioni medie di {tolower(month_str(bulletin$month))}."), "")``r ifelse(qr_high >= 150, glue::glue("In alcune località {moment02}la somma delle precipitazioni è stata meno del {qr_high} % delle precipitazioni medie mensili di {tolower(month_str(bulletin$month))}."), "")`
