``` {r echo=FALSE, results = "hide"}
all_sun_devs_above_norm <- all(regdiff$allvalues_S > 105)
all_sun_devs_below_norm <- all(regdiff$allvalues_S < 95)
all_sun_devs_normal <- all(regdiff$allvalues_S <= 105) & all(regdiff$allvalues_S >= 95)
most_sun_devs_above_norm <- regdiff$anteil_ueber_S > 0.7 & regdiff$anteil_ueber_S < 1
most_sun_devs_below_norm <- regdiff$anteil_unter_S > 0.7 & regdiff$anteil_unter_S < 1
most_sun_devs_normal <- regdiff$anteil_bereich_S > 0.7 & regdiff$anteil_bereich_S < 1

qr_low <- round(quantile(regdiff$allvalues_S,probs=0.2)/10, digits=0)*10
qr_high <- round(quantile(regdiff$allvalues_S,probs=0.8)/10, digits=0)*10

moment01 <- ifelse(bulletin$provisional, "fino alla giornata di ieri ", "") 
moment02 <- ifelse(bulletin$provisional, "fino a ieri ", "")
```


`r ifelse(all_sun_devs_above_norm, glue::glue("La durata del soleggiamento di {month_str(bulletin$month)} {bulletin$year} è superiore alla media in tutto il Paese."), "")``r ifelse(all_sun_devs_below_norm, glue::glue("In tutta la Svizzera la durata del soleggiamento di {month_str(bulletin$month)} {bulletin$year} {moment01}era inferiore alla media del periodo di riferimento 1991-2020."), "")``r ifelse(all_sun_devs_normal, glue::glue("In tutta la Svizzera la durata del soleggiamento di {month_str(bulletin$month)} {bulletin$year} {moment01}era in linea con la media del periodo di riferimento 1991-2020."), "")``r ifelse(most_sun_devs_above_norm, glue::glue("In molte regioni la durata del soleggiamento di {month_str(bulletin$month)} {bulletin$year} è superiore alla media pluriennale."), "")``r ifelse(most_sun_devs_below_norm, glue::glue("In molte regioni la durata del soleggiamento di {month_str(bulletin$month)} {bulletin$year} {moment01}era inferiore alla media."), "")``r ifelse(most_sun_devs_normal, glue::glue("In molte regioni la durata del soleggiamento di {month_str(bulletin$month)} {bulletin$year} {moment01}era in linea con la media del periodo di riferimento 1991-2020."), "")` `r ifelse(qr_low <= 50, glue::glue("In alcune regioni in {month_str(bulletin$month)} {moment02}il numero di ore di sole era inferiore al {qr_low} % della media."), "")``r ifelse(qr_high >= 130, glue::glue("In alcune località {moment02}c'è stato più del {qr_high} % del soleggiamento medio del periodo di riferimento."), "")`


